name: wallet_ui
description: "Crypto Wallet Dashboard UI"


publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  random_avatar: ^0.0.8
  cryptofont: ^1.0.2+1
  syncfusion_flutter_charts: ^24.1.44+1
  intl: ^0.18.0
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  provider: ^6.1.1
  responsive_builder: ^0.7.0
  flutter_native_splash: ^2.3.9
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/sign_w.png
    - assets/app_icon.png


flutter_native_splash:
  web: true
  color: "#16161E"
  branding: assets/sign_w.png
  image: assets/app_icon.png
  branding_mode: bottom
